<?php

define('BLINKEN_STATUS_DISABLED', 0);
define('BLINKEN_STATUS_OK', 1);
define('BLINKEN_STATUS_WARNING', 2);
define('BLINKEN_STATUS_ERROR', 3);
define('BLINKEN_STATUS_UNKNOWN', 4);
define('BLINKEN_STATUS_HOSTDOWN', 5);
